export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const FETCH_ONE_PRODUCT = 'FETCH_ONE_PRODUCT'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_BRANDS = 'FETCH_BRANDS'